name: Docker Image CI

on:
  push:
    branches: [ DISABLED ]

jobs:
  Import-GPG:
    runs-on: ubuntu-latest
    outputs:
      fingerprint: ${{ steps.commit_fingerprint.outputs.fingerprint }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Calculate HEAD commit fingerprint
        id: commit_fingerprint
        run: |
          git verify-commit --raw HEAD 2> output.log
          echo "::set-output name=fingerprint::$(grep "VALIDSIG" output.log | awk '{ print $3 }')"
#          echo "::set-output name=fingerprint::'TEST'"
        shell: bash
      - name: Check HEAD fingerprint
        run: |
          echo "HEAD fingerprint: ${{ steps.commit_fingerprint.outputs.fingerprint }}"

  GitVersion:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Display Version
        run: |
          echo "SemVer:       ${{ steps.gitversion.outputs.semVer }}"

  DockerBuild:
      if: needs.Import-GPG.outputs.fingerprint == '1BC3F6B33CB92B1DB11CD97AAA26CAA20813F5B5'
      runs-on: ubuntu-latest
      needs: [Import-GPG, GitVersion]
      env:
        FINGERPRINT: ${{needs.Import-GPG.outputs.fingerprint}}
        SEMVER: ${{needs.GitVersion.outputs.semver}}
      steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Display Fingerprint and steps.gitversion.outputs.semver
        run: |
          echo "Fingerprint: $FINGERPRINT"
          echo "SemVer: $SEMVER"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHREPOSITORY_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/build/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.SEMVER }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      

  DockerBuildError:
      if: needs.Import-GPG.outputs.fingerprint != '1BC3F6B33CB92B1DB11CD97AAA26CAA20813F5B5'
      runs-on: ubuntu-latest
      needs: [Import-GPG, GitVersion]
      steps:
        - name: Set selected color
          run: |
            echo '::set-output name=SELECTED_COLOR::red'
            echo 'BUILD NON AUTORIZZATA'